version: "3"
services:
  aware-micro:
    build:
      context: .
      args:
        DB_ENGINE: "${DB_ENGINE}"
        DB_HOST: "${DB_HOST}"
        DB_NAME: "${DB_NAME}"
        DB_USER: "${DB_USER}"
        DB_PWD: "${DB_PWD}"
        DB_PORT: "${DB_PORT}"
        SERVER_HOST: "${SERVER_HOST}"
        SERVER_PORT: "${SERVER_PORT}"
        WEBSOCKET_PORT: "${WEBSOCKET_PORT}"
    container_name: aware-micro
    depends_on:
      - aware-micro-db
    image: aware-micro
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    volumes:
      - "${PWD}:/aware-micro"
  aware-micro-db:
    container_name: aware-micro-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

networks:
  default:
    external:
      name: local-moodring
