version: "3"
services:
  aware-micro:
    build: .
    command: ["clean", "run"]
    container_name: aware-micro
    image: aware-micro
    ports:
      - "443:443"
    volumes:
      - "${PWD}:/aware-micro"
